### ISSUE TITLE
a question about 'image_list.sort()' in 'end_to_end_encoding_utils.py'

### ISSUE THREAD

**Issue by Greemwood** [gifale95/eeg_encoding#3]
Thanks very much for excellent work! I have a question about the eeg image sort problem. In end_to_end_encoding_utils.py, there are two image_list.sort() functions in lin 41 and 59.  Why use this function? Won't this destroy the order in which the EEG and image are already aligned?
![image](https://github.com/gifale95/eeg_encoding/assets/76138532/5f1eed86-c6b9-44f2-a1ef-c8e4ea5845d5)

**Comment by gifale95** [comment]
Hi, during data collection we also numbered/sorted the image conditions based on the same "image_list.sort()" order, so to make the brain responses conditions order identical to the order of the sorted images (i.e., brain response condition 1 corresponds to sorted image 1). Here we are sorting the image lists just to make sure that the same order is preserved, so that the brain responses will be correctly aligned with the corresponding images.

**Comment by Greemwood** [comment]
Thank you so much for such a timely response! You said the image conditions order  during collection is the same as "image_list.sort()", which is means, the 10 pics of the same concepts appear in turn, and another concept, and so on. Shouldn't the order be shuffled? I have just read the preprocessing_untils.py
![image](https://github.com/gifale95/eeg_encoding/assets/76138532/ea1f6105-31ea-423c-a503-7e97832191f5)
It seems that the order of the eeg data is sorted by event. 
And another question, why max_rep is 2 for training, shouldn't if be 4?

**Comment by gifale95** [comment]
Yes, the image presentation order was randomized during data collection. What I meant is that, for the data collection, the image conditions were given unique IDs based on "image_list.sort()". The preprocessed EEG data is also formatted based on these sorted unique image conditions IDs (https://osf.io/w28xy) (i.e., the first dimension of the preprocessed EEG data corresponds to the sorted image conditions IDs). In the "end_to_end_encoding_utils.py" script the images list is then sorted so to match the same sorting of the first EEG preprocessed data dimension.

Across all 4 sessions there are 4 repeats for each training image condition. However, in each session we only collected 2 repeats for each training image condition. And since the epoching is performed independently for each session, "max_rep" is set to 2.

**Comment by Greemwood** [comment]
Oh, I saw this reply just now, and I eventually get it, Thank you for your patience~
